[package]
name = "bern-arch"
version = "0.4.0"
authors = ["Stefan Lüthi <stefan.luethi@outlook.com>"]
edition = "2021"
license = "MIT"
categories = ["embedded", "no-std"]
keywords = ["embedded", "no_std", "cortex-m", "iot", "rtos"]
description = "Bern RTOS hardware specific implementation."
documentation = "https://docs.rs/bern-arch"
repository = "https://gitlab.com/bern-rtos/bern-rtos"
homepage = "https://bern-rtos.org"

[dependencies]
bern-units = "0.1"

[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dependencies]
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }

[target.'cfg(not(target_os = "none"))'.dependencies]
mockall = "0.11"

[package.metadata.docs.rs]
targets = [
    "thumbv7em-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv7m-none-eabi",
]
